/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WWorkspaceSlugRouteImport } from './routes/w.$workspaceSlug'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WWorkspaceSlugProjectsRouteImport } from './routes/w.$workspaceSlug.projects'
import { Route as WWorkspaceSlugTeamRouteImport } from './routes/w.$workspaceSlug.team'
import { Route as WWorkspaceSlugProjectsIndexRouteImport } from './routes/w.$workspaceSlug.projects.index'
import { Route as WWorkspaceSlugProjectsNewRouteImport } from './routes/w.$workspaceSlug.projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugRoute = WWorkspaceSlugRouteImport.update({
  id: '/w/$workspaceSlug',
  path: '/w/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceSlugProjectsRoute = WWorkspaceSlugProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WWorkspaceSlugRoute,
} as any)
const WWorkspaceSlugTeamRoute = WWorkspaceSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WWorkspaceSlugRoute,
} as any)
const WWorkspaceSlugProjectsIndexRoute =
  WWorkspaceSlugProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WWorkspaceSlugProjectsRoute,
  } as any)
const WWorkspaceSlugProjectsNewRoute =
  WWorkspaceSlugProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => WWorkspaceSlugProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$workspaceSlug/projects': typeof WWorkspaceSlugProjectsRouteWithChildren
  '/w/$workspaceSlug/team': typeof WWorkspaceSlugTeamRoute
  '/w/$workspaceSlug/projects/new': typeof WWorkspaceSlugProjectsNewRoute
  '/w/$workspaceSlug/projects/': typeof WWorkspaceSlugProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$workspaceSlug/team': typeof WWorkspaceSlugTeamRoute
  '/w/$workspaceSlug/projects/new': typeof WWorkspaceSlugProjectsNewRoute
  '/w/$workspaceSlug/projects': typeof WWorkspaceSlugProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/w/$workspaceSlug': typeof WWorkspaceSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/w/$workspaceSlug/projects': typeof WWorkspaceSlugProjectsRouteWithChildren
  '/w/$workspaceSlug/team': typeof WWorkspaceSlugTeamRoute
  '/w/$workspaceSlug/projects/new': typeof WWorkspaceSlugProjectsNewRoute
  '/w/$workspaceSlug/projects/': typeof WWorkspaceSlugProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/w/$workspaceSlug'
    | '/workspaces/new'
    | '/api/auth/$'
    | '/w/$workspaceSlug/projects'
    | '/w/$workspaceSlug/team'
    | '/w/$workspaceSlug/projects/new'
    | '/w/$workspaceSlug/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/w/$workspaceSlug'
    | '/workspaces/new'
    | '/api/auth/$'
    | '/w/$workspaceSlug/team'
    | '/w/$workspaceSlug/projects/new'
    | '/w/$workspaceSlug/projects'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/w/$workspaceSlug'
    | '/workspaces/new'
    | '/api/auth/$'
    | '/w/$workspaceSlug/projects'
    | '/w/$workspaceSlug/team'
    | '/w/$workspaceSlug/projects/new'
    | '/w/$workspaceSlug/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WWorkspaceSlugRoute: typeof WWorkspaceSlugRouteWithChildren
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug': {
      id: '/w/$workspaceSlug'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug'
      preLoaderRoute: typeof WWorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceSlug/projects': {
      id: '/w/$workspaceSlug/projects'
      path: '/projects'
      fullPath: '/w/$workspaceSlug/projects'
      preLoaderRoute: typeof WWorkspaceSlugProjectsRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/team': {
      id: '/w/$workspaceSlug/team'
      path: '/team'
      fullPath: '/w/$workspaceSlug/team'
      preLoaderRoute: typeof WWorkspaceSlugTeamRouteImport
      parentRoute: typeof WWorkspaceSlugRoute
    }
    '/w/$workspaceSlug/projects/': {
      id: '/w/$workspaceSlug/projects/'
      path: '/'
      fullPath: '/w/$workspaceSlug/projects/'
      preLoaderRoute: typeof WWorkspaceSlugProjectsIndexRouteImport
      parentRoute: typeof WWorkspaceSlugProjectsRoute
    }
    '/w/$workspaceSlug/projects/new': {
      id: '/w/$workspaceSlug/projects/new'
      path: '/new'
      fullPath: '/w/$workspaceSlug/projects/new'
      preLoaderRoute: typeof WWorkspaceSlugProjectsNewRouteImport
      parentRoute: typeof WWorkspaceSlugProjectsRoute
    }
  }
}

interface WWorkspaceSlugProjectsRouteChildren {
  WWorkspaceSlugProjectsNewRoute: typeof WWorkspaceSlugProjectsNewRoute
  WWorkspaceSlugProjectsIndexRoute: typeof WWorkspaceSlugProjectsIndexRoute
}

const WWorkspaceSlugProjectsRouteChildren: WWorkspaceSlugProjectsRouteChildren =
  {
    WWorkspaceSlugProjectsNewRoute: WWorkspaceSlugProjectsNewRoute,
    WWorkspaceSlugProjectsIndexRoute: WWorkspaceSlugProjectsIndexRoute,
  }

const WWorkspaceSlugProjectsRouteWithChildren =
  WWorkspaceSlugProjectsRoute._addFileChildren(
    WWorkspaceSlugProjectsRouteChildren,
  )

interface WWorkspaceSlugRouteChildren {
  WWorkspaceSlugProjectsRoute: typeof WWorkspaceSlugProjectsRouteWithChildren
  WWorkspaceSlugTeamRoute: typeof WWorkspaceSlugTeamRoute
}

const WWorkspaceSlugRouteChildren: WWorkspaceSlugRouteChildren = {
  WWorkspaceSlugProjectsRoute: WWorkspaceSlugProjectsRouteWithChildren,
  WWorkspaceSlugTeamRoute: WWorkspaceSlugTeamRoute,
}

const WWorkspaceSlugRouteWithChildren = WWorkspaceSlugRoute._addFileChildren(
  WWorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WWorkspaceSlugRoute: WWorkspaceSlugRouteWithChildren,
  WorkspacesNewRoute: WorkspacesNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
